baseURL: "https://rafaelbarduzzi.github.io/" 
title: Rafael F. Barduzzi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        # - name: Data
        #   url: data/
        #   weight: 4

params:
    description: "This website hosts Rafael F. Barduzzi's research papers, curriculum vitae, and contact information."
    author: Rafael F. Barduzzi
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Rafael F. Barduzzi
          subtitle: "<div style='text-align: justify;'>I am a Ph.D. student in the Comparative Biology program at the University of São Paulo (USP), Ribeirão Preto campus. My research so far has primarily focused on pollen morphological diversity and evolution in mimosoid plants. Currently, I am investigating lineage diversification and morphological evolution across the plant genus Mimosa L. I have a broad interest in the study of the morphological diversity of organisms and its connections to taxonomy, phylogenetic relationships, and functional diversity.</div>"
          imageUrl: "picture.jpg"
          imageWidth: 170
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            # - name: Data
            #   url: data/

    socialIcons:
        - name: CV
          url: CV_RFBarduzzi.pdf
        - name: Email
          url: mailto:rfbarduzzi@gmail.com
        - name: ResearchGate
          url: https://www.researchgate.net/profile/Rafael-F-Barduzzi
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=LAA30yMAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/rafaelbarduzzi
        - name: Linkedin
          url: https://www.linkedIn.com/in/rafael-barduzzi
        - name: Bluesky
          url: https://bsky.app/profile/barduzzi-rafael.bsky.social
        - name: Instagram
          url: https://www.instagram.com/barduzzi_rafael

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rafael F. Barduzzi"
      icon: plant.ico
      iconHeight: 30

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2